---
jobs:
- name: some-job
  plan:
  - task: wait
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
          initial_version: pipeline-image-2
      run:
        path: echo
        args: ['Hello, world!']
