jobs:
- name: interruptible-job
  interruptible: true
  plan:
  - task: wait-forever
    timeout: 1h
    config:
      platform: linux

      image_resource:
        type: mock
        source: {mirror_self: true}

      run:
        path: sh
        args:
        - -c
        - |
          while sleep 1; do
            echo waiting forever...
          done
