jobs:
- name: unit
  plan:
  - task: run
    config:
      platform: linux
      image_resource:
        type: mock
        source: {mirror_self: true}
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo plain-secret=((foo))
          echo nested-secret=((caz.baz))
